---
- hosts: web
  become: yes
  vars:
    HOST:
      platform: amd64
      subdomain: www
      init: systemd
    BOSUN_AGENT:
      install: download
      download_url: "https://github.com/bosun-monitor/bosun/releases/download/0.5.0/scollector-linux-{{ HOST.platform|lower }}"
      upgrade: No
      init: "{{ HOST.init }}"
      server:
        protocol: http
        host: home.xalg.im
        port: 8070
      hostname: "www.xalg.im"
      domain: "xalg.im"
      hostgroup:  system
      common:
        tags:
          domain: "slac.stanford.edu"
          hosttype: openstack
      external_collectors:
        dir: /usr/share/scollector/external_collectors
        
  roles:
    - { role: ansible-role-bosun_agent, tags: [ 'bosun_agent' ], _bosun_agent: "{{ BOSUN_AGENT }}" }